// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"di/services"
)

// Injectors from wire.go:

func InitializeServices() (*ServiceContainer, error) {
	serviceContainer, err := NewServiceContainer()
	if err != nil {
		return nil, err
	}
	return serviceContainer, nil
}

// wire.go:

type ServiceContainer struct {
	ServiceA *services.ServiceA
	ServiceB *services.ServiceB
}

func NewServiceContainer() (*ServiceContainer, error) {
	serviceA := services.NewServiceA()
	serviceB := services.NewServiceB()

	serviceA.SetServiceB(serviceB)
	serviceB.SetServiceA(serviceA)

	return &ServiceContainer{
		ServiceA: serviceA,
		ServiceB: serviceB,
	}, nil
}
